// src/components/react/SidebarToggleButton.tsx
import {useState} from "react";
import '../../styles/global.css'

function SidebarToggleButton() {

  const [state, setState] = useState('menu');
  const sidebar = document.getElementById('sidebar') as HTMLSpanElement;

  function toggleSidebar() {

    if(state === 'menu') {
      expandSidebar()
    } else {
      collapseSidebar()
    }
  }

  function expandSidebar() {
    setState(state === 'menu' ? 'close' : 'menu');
    sidebar.style.left = '0px';
    sidebar.style.transition = '800ms cubic-bezier(0.34, 1.56, 0.64, 1)';
  }

  function collapseSidebar() {
    setState(state === 'menu' ? 'close' : 'menu');
    sidebar.style.left = sidebar.style.width;
    sidebar.style.transition = '800ms cubic-bezier(0.36, 0, 0.66, -0.56)';
  }

  document.addEventListener('astro:after-swap', event => {
      collapseSidebar();
  });

  return (
      <>
        <button className={"material-symbols-rounded text-base p-2 text-white mt-1 ml-1 hover:bg-blue-500 duration-300 rounded-lg bg-transparent select-none hover:ring-4 hover:ring-blue-500/50 cursor-pointer border-[1px] border-white/10"} title={"Toggle Sidebar"} onClick={toggleSidebar} id={"material-icon"}>{state}</button>
      </>
  )

}

export default SidebarToggleButton;

// src/components/svelte/SidebarToggleButton.svelte
<script>
  import {onMount} from 'svelte';
  import '@styles/global.css';

  let state = 'menu';
  let sidebar;

  onMount(() => {
    sidebar = document.getElementById('sidebar');

    const astroHandler = () => collapseSidebar();
    document.addEventListener('astro:after-swap', astroHandler);

    return () => {
      document.removeEventListener('astro:after-swap', astroHandler);
    };
  });

  function toggleSidebar() {
    if (state === 'menu') {
    expandSidebar();
  } else {
    collapseSidebar();
  }
  }

  function expandSidebar() {
    state = state === 'menu' ? 'close' : 'menu';
    if (sidebar) {
      sidebar.style.left = '0px';
      sidebar.style.transition = '800ms cubic-bezier(0.22, 1, 0.36, 1)';
    }
  }

  function collapseSidebar() {
    state = state === 'menu' ? 'close' : 'menu';
    if (sidebar) {
      sidebar.style.left = sidebar.style.width;
      sidebar.style.transition = '800ms cubic-bezier(0.83, 0, 0.17, 1)';
    }
  }
</script>

<button
    class="material-symbols-rounded w-auto h-full aspect-square text-white hover:bg-spacegamedev-primary duration-300 bg-transparent select-none hover:ring-4 hover:ring-spacegamedev-primary/50 cursor-pointer border-r border-white/10"
    title="Toggle Sidebar"
    on:click={toggleSidebar}
    id="material-icon"
>
  {state}
</button>
